### ISSUE TITLE
Validate duplicates values in ENUM of input schema

### ISSUE THREAD

**Issue by mtrunkat** [apify/apify-shared-js#133]
@drobnikj commented on [Sun Oct 25 2020](https://github.com/apify/apify-worker/issues/180)

It is possible to build actor with input schema with duplicates enum values, but it is not possible to run it.
It throws error
```
{"time":"2020-10-25T19:12:32.311Z","level":"ERROR","msg":"Internal server error","pid":2115,"rt":"actors.runList","mth":"POST","ip":"86.49.247.254","ct":"application/json; charset=UTF-8","cl":"408","http":0,"prm":{"actorId":"dFGHFa6jQ4sRvQlaN"},"q":{"build":"latest"},"tkn":1,"userId":"RWnGtczwPrB3uTMak","impersonatingUserId":"RWnGtczwPrB3uTMak","dur":11,"origin":"DEVELOPMENT","type":"internal-server-error","exception":{"name":"Error","message":"schema is invalid: data.properties['language'].enum should NOT have duplicate items (items ## 0 and 2 are identical)","stack":"Error: schema is invalid: data.properties['language'].enum should NOT have duplicate items (items ## 0 and 2 are identical)\n    at Ajv.validateSchema (/home/apifier/api/node_modules/ajv/lib/ajv.js:178:16)\n    at Ajv._addSchema (/home/apifier/api/node_modules/ajv/lib/ajv.js:307:10)\n    at Ajv.compile (/home/apifier/api/node_modules/ajv/lib/ajv.js:113:24)\n    at validateInputOrThrow (/home/apifier/api/node_modules/@apify-packages/apifier-storage/src/actor_tasks/input_schema.server.js:54:25)\n    at processInputUsingSchema (/home/apifier/api/node_modules/@apify-packages/apifier-storage/src/actor_jobs/actor_jobs.server.js:353:11)\n    at ActorRunner.runActor (/home/apifier/api/node_modules/@apify-packages/apifier-storage/src/actor_jobs/actor_jobs.server.js:553:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async runActorApiWrapper (/home/apifier/api/src/lib/actor_jobs.js:188:17)\n    at async runListPost (/home/apifier/api/src/routes/actors/run_list.js:91:15)"}}
```

see more in https://apifier.slack.com/archives/C0L33UM7Z/p1593775135042800

**Comment by fnesveda** [comment]
Another report of this:
https://apifier.slack.com/archives/C0L33UM7Z/p1660641367339339
