### ISSUE TITLE
Why does apify-shared npm package print 'log error'

### ISSUE THREAD

**Issue by microworlds** [apify/apify-shared-js#144]
Using the [apify-shared
][1] npm package, when I try to run a project, I get the error message:

```js
[INFO] 08:52:24 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 3.9.9)
Error: Options "level" must be one of log.LEVELS enum!
    at new Log (/usr/src/app/node_modules/apify-shared/log.js:37:60)
    at Object.<anonymous> (/usr/src/app/node_modules/apify-shared/log.js:182:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/usr/src/app/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.nodeDevHook [as .js] (/usr/src/app/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
[ERROR] 08:52:37 Error: Options "level" must be one of log.LEVELS enum!
```

I have no clue of what is causing the error above. What can possibly cause such an error to trigger? Funny enough, running the same project with the same settings on the same docker instance works correctly without showing any errors.

PS: I am running it on docker

Any assistance will greatly be appreciated, Thank you!

  [1]: https://www.npmjs.com/package/apify-shared

**Comment by microworlds** [comment]
I've figured it out:
In the `.env` file, replacing the line `APIFY_LOG_LEVEL=info` with `APIFY_LOG_LEVEL=INFO` solved the problem :sweat_smile:. So the issue was resolved by switching from lower to upper case :man_dancing:
